// import "./globals.css";
// import Providers from "./Providers";

// export const metadata = {
//   title: "Trivia App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import Providers from "./Providers";

export const metadata = {
  title: "Trivia App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
